spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: bin-route
          uri: https://cn.bing.com
          predicates:
            - name: Path
              args:
                pattern: /search
            - name: Query
              args:
                param: q
                regexp: haha
#            - Vip=user,leifengyang
            - name: Vip
              args:
                param: user
                value: leifengyang
          order: 10
          metadata:
            hello: world
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
          filters: # /api/order/ab/c -> /ab/c
            - RewritePath=/api/order/?(?<segment>.*), /${segment}
            - OnceToken=X-Response-Token, jwt
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*), /${segment}
          order: 2
      default-filters:
        - AddResponseHeader=X-Response-Foo, 123