spring:
  cloud:
    gateway:
      routes:
        - id: google-route
          uri: https://google.com
          predicates:
            - Path=/**
          order: 10
          metadata:
            hello: world
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path
              args:
                patterns: /api/order/**
                matchTrailingSlash: true
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          order: 2